"""Site validation (SPEC 5): confirm each candidate station exists in IEM, take its
coordinates from IEM metadata, and check it has enough night-time sky reports.
"""

from __future__ import annotations

import datetime as dt
import logging
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import yaml

from skytrust.config import CONFIG_DIR, Settings
from skytrust.data import iem
from skytrust.data.http import HttpClient

log = logging.getLogger(__name__)


@dataclass
class SiteCheck:
    id: str
    terrain_class: str
    meta: dict | None
    coverage_by_year: dict[int, float]
    coverage_total: float
    passed: bool
    note: str = ""


def year_chunks(start: dt.date, end: dt.date) -> list[tuple[dt.datetime, dt.datetime]]:
    """Split [start, end] into calendar-year UTC windows (IEM etiquette: one station-year
    per request). The end bound is exclusive, so the last chunk ends the day after `end`."""
    chunks = []
    for year in range(start.year, end.year + 1):
        lo = max(dt.date(year, 1, 1), start)
        hi = min(dt.date(year + 1, 1, 1), end + dt.timedelta(days=1))
        chunks.append(
            (
                dt.datetime.combine(lo, dt.time(), tzinfo=dt.UTC),
                dt.datetime.combine(hi, dt.time(), tzinfo=dt.UTC),
            )
        )
    return chunks


def check_site(
    client: HttpClient,
    settings: Settings,
    site_id: str,
    terrain_class: str,
    meta: dict | None,
    end: dt.date,
    refresh: bool = False,
) -> SiteCheck:
    sv = settings.raw["site_validation"]
    if meta is None:
        return SiteCheck(site_id, terrain_class, None, {}, 0.0, False, "not found in IEM network")
    src = settings.sources
    frames = [
        iem.parse_asos_csv(
            iem.fetch_asos_csv(
                client, src["iem_asos_url"], site_id, lo, hi, src["iem_report_types"], refresh
            )
        )
        for lo, hi in year_chunks(settings.history_start, end + dt.timedelta(days=1))
    ]
    obs = pd.concat(frames, ignore_index=True)
    hourly = iem.hourly_cover(obs, settings.sky_cover_mapping)
    nights = iem.proxy_night_hours(
        settings.history_start, end, meta["timezone"], sv["proxy_night_local_hours"]
    )
    by_year = {
        year: iem.night_coverage(hourly, nights[nights.year == year])
        for year in sorted(set(nights.year))
    }
    total = iem.night_coverage(hourly, nights)
    passed = total >= sv["min_night_coverage"]
    note = "AWOS (not ASOS) station" if meta.get("is_awos") else ""
    return SiteCheck(site_id, terrain_class, meta, by_year, total, passed, note)


def write_sites_yaml(checks: list[SiteCheck], path: Path | None = None) -> Path:
    """Write the passing sites to config/sites.yaml with metadata straight from IEM."""
    path = path or CONFIG_DIR / "sites.yaml"
    sites = [
        {
            "id": c.id,
            "name": c.meta["name"],
            "lat": c.meta["lat"],
            "lon": c.meta["lon"],
            "elevation_m": c.meta["elevation_m"],
            "terrain_class": c.terrain_class,
            "timezone": c.meta["timezone"],
        }
        for c in checks
        if c.passed and c.meta
    ]
    header = "# Generated by `python -m skytrust validate-sites` from IEM CA_ASOS metadata.\n"
    path.write_text(header + yaml.safe_dump({"sites": sites}, sort_keys=False))
    return path


def validate_sites(
    client: HttpClient, settings: Settings, end: dt.date, refresh: bool = False
) -> list[SiteCheck]:
    src = settings.sources
    candidates = settings.raw["site_validation"]["candidates"]
    network = iem.fetch_network(client, src["iem_network_url"], src["iem_network"])
    meta = iem.parse_network_geojson(network, [c["id"] for c in candidates])
    checks = []
    for cand in candidates:
        log.info("Checking %s", cand["id"])
        checks.append(
            check_site(
                client,
                settings,
                cand["id"],
                cand["terrain_class"],
                meta.get(cand["id"]),
                end,
                refresh,
            )
        )
    return checks
